import daisyui from "daisyui";
/** @type {import('tailwindcss').Config} */

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "retro",
      "cyberpunk",
      "valentine",
      "hallows",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "outrun",
      "ocean",
      "forest",
      "chocolate",
      "black",
      "luxury",
      "dracula",
      "aqua",
      "lofi",
      "pastel",
      "wireframe",
      "neon",
      "garden",
      "vanilla",
      "ghost",
      "lemonade",
      "acid",
      "sea",
      "coffee",
      "bubblegum",
      "sunset",
      "winter",
      "dim",
      "nord",
      "night",
      "autumn",
      "cmyk",
      "wireframe",
      "retro",
    ],
  },
};
